server:
  port: 8002

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306?springcloudDB?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 33063306
#    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.thm.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true